package schema

import (
	_ "embed"
	"encoding/json"
	"fmt"
)

// optionsJSON is the checked-in option schema, compiled into the binary. It is
// regenerated by cmd/schemagen (see gen.go); no runtime file or SCHEMA_PATH env.
//
//go:embed options.json
var optionsJSON []byte

// Schema is the ordered, grouped list of option descriptors.
type Schema struct {
	Options []Option
}

// Load parses the embedded options.json into a Schema.
func Load() (*Schema, error) {
	return parse(optionsJSON)
}

// parse decodes a JSON array of Option into a Schema.
func parse(data []byte) (*Schema, error) {
	var opts []Option
	if err := json.Unmarshal(data, &opts); err != nil {
		return nil, fmt.Errorf("parse options.json: %w", err)
	}
	return &Schema{Options: opts}, nil
}

// Get returns the option with the given dotted key.
func (s *Schema) Get(key string) (Option, bool) {
	for _, o := range s.Options {
		if o.Key == key {
			return o, true
		}
	}
	return Option{}, false
}

// Groups returns group names in first-seen (file) order.
func (s *Schema) Groups() []string {
	var gs []string
	seen := map[string]bool{}
	for _, o := range s.Options {
		if !seen[o.Group] {
			seen[o.Group] = true
			gs = append(gs, o.Group)
		}
	}
	return gs
}

// InGroup returns the options in group g, in schema order.
func (s *Schema) InGroup(g string) []Option {
	var out []Option
	for _, o := range s.Options {
		if o.Group == g {
			out = append(out, o)
		}
	}
	return out
}
